### ISSUE TITLE
Connection Fails with BlockingIOError: [Errno 115] Operation now in progress

### ISSUE THREAD

**Issue by NolanGarrett** [smar000/jlr2mqtt#2]
This issue was originally discussed on the [OH2 forum](https://community.openhab.org/t/jaguar-incontrol-binding/65829).

```
2020-04-30 11:06:18,650 - INFO - Connecting to mqtt server 127.0.0.1
Traceback (most recent call last):
  File "jlr2mqtt.py", line 579, in <module>
    mqtt_client = initialise_mqtt_client(mqtt.Client(client_id=MQTT_CLIENTID))
  File "jlr2mqtt.py", line 108, in initialise_mqtt_client
    mqtt_client.connect(MQTT_SERVER, port=1883, keepalive=0, bind_address="")
  File "/usr/local/lib/python3.6/dist-packages/paho/mqtt/client.py", line 937, in connect
    return self.reconnect()
  File "/usr/local/lib/python3.6/dist-packages/paho/mqtt/client.py", line 1071, in reconnect
    sock = self._create_socket_connection()
  File "/usr/local/lib/python3.6/dist-packages/paho/mqtt/client.py", line 3522, in _create_socket_connection
    return socket.create_connection(addr, source_address=source, timeout=self._keepalive)
  File "/usr/lib/python3.6/socket.py", line 724, in create_connection
    raise err
  File "/usr/lib/python3.6/socket.py", line 713, in create_connection
    sock.connect(sa)
BlockingIOError: [Errno 115] Operation now in progress
```

The above error occurs when using the local LAN IP and the localhost IP. Testing using the [guide here](https://www.vultr.com/docs/how-to-install-mosquitto-mqtt-broker-server-on-ubuntu-16-04) confirms the mosquitto server is working properly and subscribe/publish works.

Python version: 3.6.9

**Comment by smar000** [comment]
Can you share your `.cfg` file contents as well. Also how many network cards do you have in your machine, and their ips. 

Also I have pushed a slightly updated version. Can you try this, and see if you get the same error.

If that still does not work, can you try running the following code interactively in a python3 console (replacing `127.0.0.1` with your MQTT broker ip):

```
import paho.mqtt.client as mqtt
mqtt_client = mqtt.Client(client_id="jlr2mqtt")
mqtt_client.connect("127.0.0.1", port=1883, keepalive=0, bind_address="")
```

Thanks

**Comment by NolanGarrett** [comment]
I can confirm this issue exists interactively within the console. My .cfg file is the default with the only changes being my credentials. The updated version did not resolve the issue. 

I am guessing that since I am having this problem in the console, this means it's not a problem with your code and I need to further troubleshoot my system.

**Comment by NolanGarrett** [comment]
This issue is identified [here](https://github.com/eclipse/paho.mqtt.python/issues/473). When connecting via the python3 console, I can confirm I do not receive this error with a keepalive value > 0.

**Comment by smar000** [comment]
Ah yes, I recall that I had disabled the `keepalive` messages due to some other timeout related issues at the time, and did not turn this back on or investigate further. But a `keepalive` of `0` is/was valid, so something must have changed either in the `paho-mqtt` library or possibly mosquitto (less likely, as you had the same problem with the openHAB embedded broker). For reference, I am on version 1.4.0 of the `paho-mqtt`.

In any event, I'll upload a new release with keepalive default to 60 seconds (and a corresponding optional configuration parameter) shortly.
