### ISSUE TITLE
Multiple Vehicle Support

### ISSUE THREAD

**Issue by NolanGarrett** [smar000/jlr2mqtt#3]
The script only appears to check for the first vehicle status:

`jlr_connection.vehicles[0]`

This is called only a handful of times in the code. I have two vehicles on the same account, so to access my second vehicle I believe I must call:

`jlr_connection.vehicles[1]`

Could the script and configuration file be enhanced to allow me to pass this array index through via a config file setting?

**Comment by smar000** [comment]
Sure, I'll have a look at it in the next day or so.

EDIT: Actually I just had a look at the code. It is a little more involved than just adding an optional parameter for the vehicle index, as all the mqtt publishing is to the same `jlr2mqtt` topic (and so each vehicle will end up overwriting the data from other vehicles). 

I will have a think on it and see what I can come up with.

**Comment by smar000** [comment]
Can you try the version from the `multi_vehicle` branch and see how that works for you. This version should support both your vehicles from the single script. Note that you will need to include the `vehicle_index` parameter when when sending commands.

Do let me know how you get on.

**Comment by smar000** [comment]
Hi @NolanGarrett 

Haven't heard back from you, so will close this issue for now. If you still have problems, don't hesitate to reach out.

**Comment by NolanGarrett** [comment]
My apologies, I've been tied up and beyond a quick clone and test (which worked), I didn't go through the full implementation and I am still running manually modified scripts. This did work in my test though, so thank you very much!

**Comment by smar000** [comment]
No problem. Glad to hear it is working for you.
