### ISSUE TITLE
ssl.SSLWantReadError: The operation did not complete (read). When "keep alive is set to 0" in paho-mqtt version 1.4 MQTTs has SSL issues.

### ISSUE THREAD

**Issue by Kavithaa-kannadasan** [smar000/jlr2mqtt#4]
Previously i was using paho-mqtt version 1.5.0. In which i faced a problem if the keep-alive is set to 0. Then I referred to this link (I also had the same problem) [https://github.com/smar000/jlr2mqtt/issues/2] #2.  Then i tried with paho mqtt version 1.4. In which, It worked fine for non secure MQTT. Where as for secure MQTT, I got the following error

>  mqttc.connect(broker,` port=port, keepalive =0) #returns on_connect()
>  File "/usr/local/lib/python3.6/dist-packages/paho/mqtt/client.py", line 839, in connect
>     return self.reconnect()
>   File "/usr/local/lib/python3.6/dist-packages/paho/mqtt/client.py", line 994, in reconnect
>     sock.do_handshake()
>   File "/usr/lib/python3.6/ssl.py", line 1077, in do_handshake
>     self._sslobj.do_handshake()
>   File "/usr/lib/python3.6/ssl.py", line 689, in do_handshake
>     self._sslobj.do_handshake()
> ssl.SSLWantReadError: The operation did not complete (read) (_ssl.c:852)

If i set the keepalive > 0 it is working fine for MQTTs.
Could you please explain me what could be the cause of this following error?

**Comment by smar000** [comment]
We came across this issue a few days ago - see https://github.com/smar000/jlr2mqtt/issues/2. 

Something has changed in the paho library. I have not really looked into what/why etc. I have updated the code to use a default keeplaive of 60, which should work for most cases.

**Comment by Kavithaa-kannadasan** [comment]
@smar000 Thank you for your reply.
okay.. Ya if keepalive is > 0 its working fine.

**Comment by Kavithaa-kannadasan** [comment]
@smar000 Thank you for your reply.
okay.. Ya if keepalive is > 0 its working fine.
